version: "2"
services:
  mysql:
    container_name: tutorial_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    image: mysql:8.0.13
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: "test_pass"
      MYSQL_USER: "test"
      MYSQL_PASS: "pass"
    volumes:
      - my-datavolume:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  my-datavolume:
